In [1]:
import pandas as pd

In [2]:
serie = pd.Series(["Ana","Bruno","Camila","Bia"], name="Nomes")

In [3]:
print(serie)

0       Ana
1     Bruno
2    Camila
3       Bia
Name: Nomes, dtype: str

In [4]:
df = pd.DataFrame({"id_cliente":[1,2,3,4], "cliente":["Ana","Bruno","Camila","Bia"]})

In [5]:
print(df)

   id_cliente cliente
0           1     Ana
1           2   Bruno
2           3  Camila
3           4     Bia

In [6]:
type(serie)

pandas.Series

In [7]:
type(df)

pandas.DataFrame

In [8]:
type(df['cliente'])

pandas.Series

Contexto: Você acaba de receber uma pequena amostra de cadastros de clientes da Connecta+ e precisa fazer uma verificação rápida: quantos registros vieram, quais colunas estão disponíveis e como são os primeiros dados.

In [9]:
import pandas as pd

df = pd.DataFrame({
    "cliente_id": [101, 102, 103, 104, 105, 106],
    "nome": ["Ana Costa", "Bruno Lima", "Carla Dias", "Diego Alves", "Eva Santos", "Felipe Ramos"],
    "segmento": ["vip", "regular", "premium", "regular", "vip", "premium"],
    "valor_total": [12500.00, 3200.00, 7800.00, 1500.00, 15000.00, 6400.00]
})

In [10]:
print(df)

   cliente_id          nome segmento  valor_total
0         101     Ana Costa      vip      12500.0
1         102    Bruno Lima  regular       3200.0
2         103    Carla Dias  premium       7800.0
3         104   Diego Alves  regular       1500.0
4         105    Eva Santos      vip      15000.0
5         106  Felipe Ramos  premium       6400.0

Tarefa: Responda usando Pandas:

Quantas linhas e colunas a base possui?

In [11]:
df.shape

(6, 4)

Quais são os nomes das colunas?

In [12]:
df.columns

Index(['cliente_id', 'nome', 'segmento', 'valor_total'], dtype='str')

Mostre apenas as 3 primeiras linhas.

In [13]:
df.head(3)

   cliente_id        nome segmento  valor_total
0         101   Ana Costa      vip      12500.0
1         102  Bruno Lima  regular       3200.0
2         103  Carla Dias  premium       7800.0

Qual é o tipo do objeto retornado por df["nome"]?

In [14]:
type(df["nome"])

pandas.Series

## Leitura de Dados

In [15]:
# O 'sep' é usado aqui porque o CSV é um arquivo de texto com separadores
df_clientes_crm = pd.read_csv("/clientes_crm.csv", sep=",")

# O Excel (.xlsx) não aceita o parâmetro 'sep'
df_interacoes_clientes = pd.read_excel("/interacoes_clientes.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: '/clientes_crm.csv'

In [ ]:
df_clientes_crm.shape #Verificar as dimensões de um Dataframe ou de uma Serie

(2040, 10)

In [ ]:
df_interacoes_clientes.shape #Verificar as dimensões de um Dataframe ou de uma Serie

(10100, 8)

In [ ]:
print(df_clientes_crm)

      cliente id            nome                            email  \
0              1    Carlos Silva                              NaN
1              2    Lucas Lima         lucas.lima2548@outlook.com
2              3     Maria Silva        maria.silva4742@gmail.com
3              4  Felipe Pereira    felipe.pereira917@outlook.com
4              5     Diego Rocha                              NaN
...          ...             ...                              ...
2035         451   Patricia Lima       PATRICIA.LIMA360@EMAIL.COM
2036        1610    Carlos Costa     carlos.costa1595@outlook.com
2037        1291     Maria Rocha   maria.rocha4088@empresa.com.br
2038        1079     João Silva         joão.silva889@outlook.com
2039         255    Felipe Silva  felipe.silva9176@empresa.com.br

     data cadastro ultima compra data idade segmento cliente status cliente  \
0       2024-02-01         2024-02-05   NaN              NaN          Ativo
1       2024-01-01         2022/04/12    38          Regular          Ativo
2       27-11-2021         2024/01/29    28          Regular          Ativo
3       22-05-2023         2023/02/09    41        Premium          Inativo
4       2021-12-10         2022-01-21    61              NaN        Inativo
...            ...                ...   ...              ...            ...
2035    2022-08-28         2023-01-06   42           Premium         Ativo
2036    2023-01-15         2022-10-01    57          Premium       Inativo
2037    12/03/2021         2021-07-08    47              VIP        Ativo
2038    2023/04/05         14-08-2021    59          Premium         Ativo
2039    2021-06-26         2022/10/24   46           Regular        Inativo

     canal aquisicao   valor total
0           LinkedIn  R$ 14.265,64
1           Facebook   R$ 2.424,68
2               Site  R$ 13.006,02
3           LinkedIn   R$ 9.798,24
4           Facebook  R$ 14.084,44
...              ...           ...
2035            Site   R$ 8.987,63
2036        LinkedIn           NaN
2037        Facebook   R$ 5.518,32
2038        LinkedIn   R$ 4.300,59
2039       LinkedIn        8750,77

[2040 rows x 10 columns]

In [ ]:
print(df_clientes_crm)

      cliente id            nome                            email  \
0              1    Carlos Silva                              NaN
1              2    Lucas Lima         lucas.lima2548@outlook.com
2              3     Maria Silva        maria.silva4742@gmail.com
3              4  Felipe Pereira    felipe.pereira917@outlook.com
4              5     Diego Rocha                              NaN
...          ...             ...                              ...
2035         451   Patricia Lima       PATRICIA.LIMA360@EMAIL.COM
2036        1610    Carlos Costa     carlos.costa1595@outlook.com
2037        1291     Maria Rocha   maria.rocha4088@empresa.com.br
2038        1079     João Silva         joão.silva889@outlook.com
2039         255    Felipe Silva  felipe.silva9176@empresa.com.br

     data cadastro ultima compra data idade segmento cliente status cliente  \
0       2024-02-01         2024-02-05   NaN              NaN          Ativo
1       2024-01-01         2022/04/12    38          Regular          Ativo
2       27-11-2021         2024/01/29    28          Regular          Ativo
3       22-05-2023         2023/02/09    41        Premium          Inativo
4       2021-12-10         2022-01-21    61              NaN        Inativo
...            ...                ...   ...              ...            ...
2035    2022-08-28         2023-01-06   42           Premium         Ativo
2036    2023-01-15         2022-10-01    57          Premium       Inativo
2037    12/03/2021         2021-07-08    47              VIP        Ativo
2038    2023/04/05         14-08-2021    59          Premium         Ativo
2039    2021-06-26         2022/10/24   46           Regular        Inativo

     canal aquisicao   valor total
0           LinkedIn  R$ 14.265,64
1           Facebook   R$ 2.424,68
2               Site  R$ 13.006,02
3           LinkedIn   R$ 9.798,24
4           Facebook  R$ 14.084,44
...              ...           ...
2035            Site   R$ 8.987,63
2036        LinkedIn           NaN
2037        Facebook   R$ 5.518,32
2038        LinkedIn   R$ 4.300,59
2039       LinkedIn        8750,77

[2040 rows x 10 columns]

In [ ]:
df_interacoes_clientes = pd.read_excel("/interacoes_clientes.xlsx", sheet_name="Sheet1") # Removido o sheet_name para carregar automaticamente a primeira aba disponível
print(df_interacoes_clientes)

       id interacao  cliente id data interacao canal interacao tipo interacao  \
0                 1         268     08-04-2024           Chat           Venda
1                 2         551     08/08/2024        Telefone     Reclamação
2                 3        1823     10-03-2024        WhatsApp       Suporte
3                 4        1449     10-11-2021            Chat     Reclamação
4                 5        1688     14/12/2022            Chat          Venda
...             ...         ...            ...             ...            ...
10095          9026        1597     2023/07/25            Chat          Venda
10096          4642         478     2022-05-23       Telefone           Venda
10097          8723           5     23-12-2021           Email          Venda
10098          9737         267     18-10-2022           Email     Reclamação
10099          1112         410     2021/01/27      WhatsApp          Venda

       duracao minutos  satisfacao cliente status resolucao
0                 50.0                 1.0         Pendente
1                  NaN                 4.0        Resolvido
2                 18.0                 2.0        Resolvido
3                 56.0                 NaN        Resolvido
4                 31.0                 3.0         Pendente
...                ...                 ...              ...
10095             40.0                 2.0         Pendente
10096             16.0                 1.0         Pendente
10097             23.0                 3.0        Resolvido
10098             37.0                 NaN        Resolvido
10099             29.0                 5.0         Pendente

[10100 rows x 8 columns]

In [ ]:
df_interacoes_clientes.head()

,id interacao,cliente id,data interacao,canal interacao,tipo interacao,duracao minutos,satisfacao cliente,status resolucao
0,1,268,08-04-2024,Chat,Venda,50.0,1.0,Pendente
1,2,551,08/08/2024,Telefone,Reclamação,NaN,4.0,Resolvido
2,3,1823,10-03-2024,WhatsApp,Suporte,18.0,2.0,Resolvido
3,4,1449,10-11-2021,Chat,Reclamação,56.0,NaN,Resolvido
4,5,1688,14/12/2022,Chat,Venda,31.0,3.0,Pendente

In [ ]:
df_interacoes_clientes.sample(5) # Retorna uma amostra aleatória de 5 linhas do DataFrame

,id interacao,cliente id,data interacao,canal interacao,tipo interacao,duracao minutos,satisfacao cliente,status resolucao
2879,2880,931,14-03-2024,WhatsApp,Reclamação,18.0,1.0,Resolvido
1529,1530,434,29/05/2023,Email,Reclamação,2.0,5.0,Resolvido
1755,1756,355,07-08-2022,WhatsApp,Reclamação,50.0,NaN,Pendente
6392,6393,1043,2023-11-30,Email,Reclamação,34.0,5.0,Pendente
5879,5880,679,26/08/2022,Telefone,Dúvida,8.0,NaN,Resolvido

In [ ]:
df_clientes_crm.sample(5)

,cliente id,nome,email,data cadastro,ultima compra data,idade,segmento cliente,status cliente,canal aquisicao,valor total
1871,1872,Maria Silva,maria.silva5297@empresa.com.br,14/11/2023,24-04-2023,NaN,VIP,Ativo,LinkedIn,NaN
577,578,Thiago Gomes,thiago.gomes7181@empresa.com.br,22-04-2021,21-07-2023,30,Premium,Ativo,Indicação,"R$ 8.126,57"
1999,2000,Beatriz Souza,beatriz.souza3951@email.com,29/10/2021,2023/02/18,53,VIP,Inativo,Instagram,"4359,04"
787,788,João Pereira,joão.pereira8812@email.com,20-12-2021,2023/09/18,28,Premium,Ativo,Instagram,"R$ 4.146,05"
10,11,Pedro Gomes,NaN,29-02-2024,2021-01-21,54,Regular,Inativo,Indicação,"9152,42"

In [ ]:
df_clientes_crm.info() #Informacoes do dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   cliente id          2040 non-null   int64
 1   nome                2040 non-null   object
 2   email               1781 non-null   object
 3   data cadastro       2040 non-null   object
 4   ultima compra data  1623 non-null   object
 5   idade               1818 non-null   object
 6   segmento cliente    1812 non-null   object
 7   status cliente      2040 non-null   object
 8   canal aquisicao     2040 non-null   object
 9   valor total         1727 non-null   object
dtypes: int64(1), object(9)
memory usage: 159.5+ KB

In [ ]:
df_interacoes_clientes.info() #Informacoes do dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10100 entries, 0 to 10099
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id interacao        10100 non-null  int64
 1   cliente id          10100 non-null  int64
 2   data interacao      10100 non-null  object
 3   canal interacao     10100 non-null  object
 4   tipo interacao      10100 non-null  object
 5   duracao minutos     9417 non-null   float64
 6   satisfacao cliente  6314 non-null   float64
 7   status resolucao    10100 non-null  object
dtypes: float64(2), int64(2), object(4)
memory usage: 631.4+ KB

In [ ]:
df_interacoes_clientes.isna().sum() #Verificando a quantidade de null nas colunas

id interacao             0
cliente id               0
data interacao           0
canal interacao          0
tipo interacao           0
duracao minutos        683
satisfacao cliente    3786
status resolucao         0
dtype: int64

In [ ]:
df_interacoes_clientes.isna().mean() * 100

id interacao           0.000000
cliente id             0.000000
data interacao         0.000000
canal interacao        0.000000
tipo interacao         0.000000
duracao minutos        6.762376
satisfacao cliente    37.485149
status resolucao       0.000000
dtype: float64

In [ ]:
df_interacoes_clientes.duplicated().sum() # Identifica linhas duplicadas e soma o total delas na tabela

np.int64(100)

In [ ]:
df_clientes_crm.duplicated(subset=['cliente id']).sum() # Identifica e soma a quantidade de IDs de clientes duplicados (repetidos)

np.int64(40)

In [ ]:
df_clientes_crm["nome"]

0         Carlos Silva
1         Lucas Lima
2          Maria Silva
3       Felipe Pereira
4          Diego Rocha
             ...
2035     Patricia Lima
2036      Carlos Costa
2037       Maria Rocha
2038       João Silva
2039      Felipe Silva
Name: nome, Length: 2040, dtype: object

In [ ]:
df_clientes_crm["segmento cliente"].value_counts() #serve para fazer um levantamento de frequência. Ele agrupa cada categoria única da coluna e nos mostra a quantidade de clientes que pertencem a cada uma delas.

segmento cliente
Premium        425
Regular        423
VIP            349
Premium        106
 VIP            92
 Regular        89
 Premium        80
Regular         79
VIP             77
  Premium       35
  Regular       31
  VIP           26
Name: count, dtype: int64

In [ ]:
df_interacoes_clientes_limpo = df_interacoes_clientes.copy()
df_clientes_crm_limpo = df_clientes_crm.copy()

df_interacoes_clientes_limpo.head()
df_clientes_crm_limpo.head()

,cliente id,nome,email,data cadastro,ultima compra data,idade,segmento cliente,status cliente,canal aquisicao,valor total
0,1,Carlos Silva,NaN,2024-02-01,2024-02-05,NaN,NaN,Ativo,LinkedIn,"R$ 14.265,64"
1,2,Lucas Lima,lucas.lima2548@outlook.com,2024-01-01,2022/04/12,38,Regular,Ativo,Facebook,"R$ 2.424,68"
2,3,Maria Silva,maria.silva4742@gmail.com,27-11-2021,2024/01/29,28,Regular,Ativo,Site,"R$ 13.006,02"
3,4,Felipe Pereira,felipe.pereira917@outlook.com,22-05-2023,2023/02/09,41,Premium,Inativo,LinkedIn,"R$ 9.798,24"
4,5,Diego Rocha,NaN,2021-12-10,2022-01-21,61,NaN,Inativo,Facebook,"R$ 14.084,44"

In [ ]:
df_clientes_crm_limpo.isna().mean()*100

cliente id             0.000000
nome                   0.000000
email                 12.696078
data cadastro          0.000000
ultima compra data    20.441176
idade                 10.882353
segmento cliente      11.176471
status cliente         0.000000
canal aquisicao        0.000000
valor total           15.343137
dtype: float64

In [ ]:
df_clientes_crm_limpo['segmento cliente'] = df_clientes_crm_limpo['segmento cliente'].fillna('Não informado')
df_clientes_crm_limpo['email'] = df_clientes_crm_limpo['email'].fillna('Nao informado')

In [ ]:
df_clientes_crm_limpo.isna().mean()*100

cliente id             0.000000
nome                   0.000000
email                  0.000000
data cadastro          0.000000
ultima compra data    20.441176
idade                 10.882353
segmento cliente       0.000000
status cliente         0.000000
canal aquisicao        0.000000
valor total           15.343137
dtype: float64

In [ ]:
print(df_clientes_crm_limpo)

      cliente id            nome                            email  \
0              1    Carlos Silva                    Nao informado
1              2    Lucas Lima         lucas.lima2548@outlook.com
2              3     Maria Silva        maria.silva4742@gmail.com
3              4  Felipe Pereira    felipe.pereira917@outlook.com
4              5     Diego Rocha                    Nao informado
...          ...             ...                              ...
2035         451   Patricia Lima       PATRICIA.LIMA360@EMAIL.COM
2036        1610    Carlos Costa     carlos.costa1595@outlook.com
2037        1291     Maria Rocha   maria.rocha4088@empresa.com.br
2038        1079     João Silva         joão.silva889@outlook.com
2039         255    Felipe Silva  felipe.silva9176@empresa.com.br

     data cadastro ultima compra data idade segmento cliente status cliente  \
0       2024-02-01         2024-02-05   NaN    Não informado          Ativo
1       2024-01-01         2022/04/12    38          Regular          Ativo
2       27-11-2021         2024/01/29    28          Regular          Ativo
3       22-05-2023         2023/02/09    41        Premium          Inativo
4       2021-12-10         2022-01-21    61    Não informado        Inativo
...            ...                ...   ...              ...            ...
2035    2022-08-28         2023-01-06   42           Premium         Ativo
2036    2023-01-15         2022-10-01    57          Premium       Inativo
2037    12/03/2021         2021-07-08    47              VIP        Ativo
2038    2023/04/05         14-08-2021    59          Premium         Ativo
2039    2021-06-26         2022/10/24   46           Regular        Inativo

     canal aquisicao   valor total
0           LinkedIn  R$ 14.265,64
1           Facebook   R$ 2.424,68
2               Site  R$ 13.006,02
3           LinkedIn   R$ 9.798,24
4           Facebook  R$ 14.084,44
...              ...           ...
2035            Site   R$ 8.987,63
2036        LinkedIn           NaN
2037        Facebook   R$ 5.518,32
2038        LinkedIn   R$ 4.300,59
2039       LinkedIn        8750,77

[2040 rows x 10 columns]

In [ ]:
print(df_clientes_crm_limpo)

      cliente id            nome                            email  \
0              1    Carlos Silva                    Nao informado
1              2    Lucas Lima         lucas.lima2548@outlook.com
2              3     Maria Silva        maria.silva4742@gmail.com
3              4  Felipe Pereira    felipe.pereira917@outlook.com
4              5     Diego Rocha                    Nao informado
...          ...             ...                              ...
2035         451   Patricia Lima       PATRICIA.LIMA360@EMAIL.COM
2036        1610    Carlos Costa     carlos.costa1595@outlook.com
2037        1291     Maria Rocha   maria.rocha4088@empresa.com.br
2038        1079     João Silva         joão.silva889@outlook.com
2039         255    Felipe Silva  felipe.silva9176@empresa.com.br

     data cadastro ultima compra data idade segmento cliente status cliente  \
0       2024-02-01         2024-02-05   NaN    Não informado          Ativo
1       2024-01-01         2022/04/12    38          Regular          Ativo
2       27-11-2021         2024/01/29    28          Regular          Ativo
3       22-05-2023         2023/02/09    41        Premium          Inativo
4       2021-12-10         2022-01-21    61    Não informado        Inativo
...            ...                ...   ...              ...            ...
2035    2022-08-28         2023-01-06   42           Premium         Ativo
2036    2023-01-15         2022-10-01    57          Premium       Inativo
2037    12/03/2021         2021-07-08    47              VIP        Ativo
2038    2023/04/05         14-08-2021    59          Premium         Ativo
2039    2021-06-26         2022/10/24   46           Regular        Inativo

     canal aquisicao   valor total
0           LinkedIn  R$ 14.265,64
1           Facebook   R$ 2.424,68
2               Site  R$ 13.006,02
3           LinkedIn   R$ 9.798,24
4           Facebook  R$ 14.084,44
...              ...           ...
2035            Site   R$ 8.987,63
2036        LinkedIn           NaN
2037        Facebook   R$ 5.518,32
2038        LinkedIn   R$ 4.300,59
2039       LinkedIn        8750,77

[2040 rows x 10 columns]

In [ ]:
print(df_interacoes_clientes_limpo)

       id interacao  cliente id data interacao canal interacao tipo interacao  \
0                 1         268     08-04-2024           Chat           Venda
1                 2         551     08/08/2024        Telefone     Reclamação
2                 3        1823     10-03-2024        WhatsApp       Suporte
3                 4        1449     10-11-2021            Chat     Reclamação
4                 5        1688     14/12/2022            Chat          Venda
...             ...         ...            ...             ...            ...
10095          9026        1597     2023/07/25            Chat          Venda
10096          4642         478     2022-05-23       Telefone           Venda
10097          8723           5     23-12-2021           Email          Venda
10098          9737         267     18-10-2022           Email     Reclamação
10099          1112         410     2021/01/27      WhatsApp          Venda

       duracao minutos  satisfacao cliente status resolucao
0                 50.0                 1.0         Pendente
1                  NaN                 4.0        Resolvido
2                 18.0                 2.0        Resolvido
3                 56.0                 NaN        Resolvido
4                 31.0                 3.0         Pendente
...                ...                 ...              ...
10095             40.0                 2.0         Pendente
10096             16.0                 1.0         Pendente
10097             23.0                 3.0        Resolvido
10098             37.0                 NaN        Resolvido
10099             29.0                 5.0         Pendente

[10100 rows x 8 columns]

In [ ]:
df_interacoes_clientes_limpo['duracao minutos'] = df_interacoes_clientes_limpo['duracao minutos'].fillna(df_interacoes_clientes_limpo['duracao minutos'].mean())
df_interacoes_clientes_limpo['satisfacao cliente'] = df_interacoes_clientes_limpo['satisfacao cliente'].fillna(df_interacoes_clientes_limpo['satisfacao cliente'].mean())

In [ ]:
print(df_interacoes_clientes_limpo)

       id interacao  cliente id data interacao canal interacao tipo interacao  \
0                 1         268     08-04-2024           Chat           Venda
1                 2         551     08/08/2024        Telefone     Reclamação
2                 3        1823     10-03-2024        WhatsApp       Suporte
3                 4        1449     10-11-2021            Chat     Reclamação
4                 5        1688     14/12/2022            Chat          Venda
...             ...         ...            ...             ...            ...
10095          9026        1597     2023/07/25            Chat          Venda
10096          4642         478     2022-05-23       Telefone           Venda
10097          8723           5     23-12-2021           Email          Venda
10098          9737         267     18-10-2022           Email     Reclamação
10099          1112         410     2021/01/27      WhatsApp          Venda

       duracao minutos  satisfacao cliente status resolucao
0            50.000000             1.00000         Pendente
1            29.622066             4.00000        Resolvido
2            18.000000             2.00000        Resolvido
3            56.000000             3.02249        Resolvido
4            31.000000             3.00000         Pendente
...                ...                 ...              ...
10095        40.000000             2.00000         Pendente
10096        16.000000             1.00000         Pendente
10097        23.000000             3.00000        Resolvido
10098        37.000000             3.02249        Resolvido
10099        29.000000             5.00000         Pendente

[10100 rows x 8 columns]

In [ ]:
df_interacoes_clientes_limpo.duplicated(subset=['id interacao']).sum()

np.int64(100)

In [ ]:
df_clientes_crm_limpo.duplicated(subset=['cliente id']).sum()

np.int64(40)

In [ ]:
df_interacoes_clientes_limpo = df_interacoes_clientes_limpo.drop_duplicates(subset=['id interacao'])
df_clientes_crm_limpo = df_clientes_crm_limpo.drop_duplicates(subset=['cliente id'])

In [ ]:
df_interacoes_clientes_limpo.duplicated(subset=['id interacao']).sum()

np.int64(0)

In [ ]:
df_clientes_crm_limpo.duplicated(subset=['cliente id']).sum()

np.int64(0)

In [ ]:
df_clientes_crm_limpo.shape

(2000, 10)

In [ ]:
df_interacoes_clientes_limpo.shape

(10000, 8)

In [ ]:
df_clientes_crm_limpo["canal aquisicao"].value_counts()

canal aquisicao
LinkedIn          241
Instagram         223
Indicação         208
Site              203
Google Ads        200
Facebook          198
Indicação          62
 Google Ads        58
 LinkedIn          56
 Indicação         53
 Site              52
LinkedIn           52
Google Ads         51
 Facebook          50
 Instagram         49
Site               49
Facebook           48
Instagram          37
  LinkedIn         25
  Google Ads       18
  Facebook         18
  Site             17
  Instagram        16
  Indicação        16
Name: count, dtype: int64

In [ ]:
df_clientes_limpo["canal aquisicao"] = df_clientes_limpo["canal aquisicao"].str.strip()
df_clientes_limpo["canal aquisicao"] = df_clientes_limpo["canal aquisicao"].str.lower()

In [ ]:
df_clientes_limpo["segmento cliente"] = df_clientes_limpo["segmento cliente"].str.strip()
df_clientes_limpo["segmento cliente"] = df_clientes_limpo["segmento cliente"].str.lower()

In [ ]:
df_clientes_crm_limpo["canal aquisicao"].value_counts()

canal aquisicao
LinkedIn          241
Instagram         223
Indicação         208
Site              203
Google Ads        200
Facebook          198
Indicação          62
 Google Ads        58
 LinkedIn          56
 Indicação         53
 Site              52
LinkedIn           52
Google Ads         51
 Facebook          50
 Instagram         49
Site               49
Facebook           48
Instagram          37
  LinkedIn         25
  Google Ads       18
  Facebook         18
  Site             17
  Instagram        16
  Indicação        16
Name: count, dtype: int64

In [ ]:
df_clientes_crm_limpo["segmento cliente"].value_counts()

segmento cliente
Regular          415
Premium          414
VIP              342
Não informado    226
Premium          105
 VIP              88
 Regular          88
Regular           79
 Premium          78
VIP               75
  Premium         34
  Regular         30
  VIP             26
Name: count, dtype: int64

In [ ]:
df_clientes_crm_limpo["status cliente"].value_counts()

status cliente
Inativo        650
Ativo          645
Ativo          168
Inativo        151
 Inativo       148
 Ativo         145
  Inativo       48
  Ativo         45
Name: count, dtype: int64

In [ ]:
df_clientes_limpo['status cliente'] = df_clientes_crm_limpo['status cliente'].astype(str).str.strip()
df_clientes_limpo['status cliente'] = df_clientes_crm_limpo['status cliente'].astype(str).str.lower()

In [ ]:
df_clientes_limpo['status cliente'].value_counts()

status cliente
inativo        650
ativo          645
ativo          168
inativo        151
 inativo       148
 ativo         145
  inativo       48
  ativo         45
Name: count, dtype: int64

In [ ]:
df_interacoes_clientes_limpo['canal interacao'].value_counts()

canal interacao
Email           1626
Telefone        1616
Chat            1587
WhatsApp        1566
 Email           406
Telefone         404
WhatsApp         390
 Chat            384
Email            383
 WhatsApp        380
 Telefone        367
Chat             366
  Telefone       146
  Email          136
  Chat           124
  WhatsApp       119
Name: count, dtype: int64

In [ ]:
df_interacoes_clientes_limpo['canal interacao'] = df_interacoes_clientes_limpo['canal interacao'].str.strip()
df_interacoes_clientes_limpo['canal interacao'] = df_interacoes_clientes_limpo['canal interacao'].str.lower()

In [ ]:
df_interacoes_clientes_limpo['canal interacao'].value_counts()

canal interacao
email       2551
telefone    2533
chat        2461
whatsapp    2455
Name: count, dtype: int64

In [ ]:
df_interacoes_clientes_limpo['tipo interacao'] = df_interacoes_clientes_limpo['tipo interacao'].str.strip()
df_interacoes_clientes_limpo['tipo interacao'] = df_interacoes_clientes_limpo['tipo interacao'].str.lower()

In [ ]:
df_interacoes_clientes_limpo['tipo interacao'].value_counts()

tipo interacao
suporte       2548
venda         2526
dúvida        2510
reclamação    2416
Name: count, dtype: int64

In [ ]:
df_interacoes_clientes_limpo['status resolucao'] = df_interacoes_clientes_limpo['status resolucao'].str.strip()
df_interacoes_clientes_limpo['status resolucao'] = df_interacoes_clientes_limpo['status resolucao'].str.lower

In [ ]:
df_interacoes_clientes_limpo

,id interacao,cliente id,data interacao,canal interacao,tipo interacao,duracao minutos,satisfacao cliente,status resolucao
0,1,268,08-04-2024,chat,venda,50.000000,1.00000,<bound method StringMethods.lower of <pandas.c...
1,2,551,08/08/2024,telefone,reclamação,29.622066,4.00000,<bound method StringMethods.lower of <pandas.c...
2,3,1823,10-03-2024,whatsapp,suporte,18.000000,2.00000,<bound method StringMethods.lower of <pandas.c...
3,4,1449,10-11-2021,chat,reclamação,56.000000,3.02249,<bound method StringMethods.lower of <pandas.c...
4,5,1688,14/12/2022,chat,venda,31.000000,3.00000,<bound method StringMethods.lower of <pandas.c...
...,...,...,...,...,...,...,...,...
9995,9996,21,24/06/2023,email,suporte,29.622066,3.00000,<bound method StringMethods.lower of <pandas.c...
9996,9997,1501,05-08-2024,whatsapp,venda,14.000000,1.00000,<bound method StringMethods.lower of <pandas.c...
9997,9998,43,2023/04/30,telefone,dúvida,54.000000,1.00000,<bound method StringMethods.lower of <pandas.c...
9998,9999,1029,26/07/2021,telefone,venda,59.000000,3.02249,<bound method StringMethods.lower of <pandas.c...
9999,10000,1863,2021-12-11,whatsapp,reclamação,14.000000,5.00000,<bound method StringMethods.lower of <pandas.c...

In [ ]:
df_clientes_limpo["canal aquisicao"] = df_clientes_limpo["canal aquisicao"].str.strip()
df_clientes_limpo["canal aquisicao"] = df_clientes_limpo["canal aquisicao"].str.lower()

In [ ]:
df_clientes_limpo["canal aquisicao"].value_counts()

canal aquisicao
linkedin      374
indicação     339
google ads    327
instagram     325
site          321
facebook      314
Name: count, dtype: int64

In [ ]:
df_clientes_limpo['segmento cliente'] = df_clientes_limpo['segmento cliente'].astype(str).str.strip()
df_clientes_limpo['segmento cliente'] = df_clientes_limpo['segmento cliente'].astype(str).str.lower()

In [ ]:
df_clientes_limpo['segmento cliente'].value_counts()

segmento cliente
premium          631
regular          612
vip              531
não informado    226
Name: count, dtype: int64

In [ ]:
df_clientes_limpo['status cliente'].value_counts()

status cliente
ativo      1003
inativo     997
Name: count, dtype: int64

In [ ]:
df_clientes_limpo['status cliente'] = df_clientes_limpo['status cliente'].astype(str).str.strip()
df_clientes_limpo['status cliente'] = df_clientes_limpo['status cliente'].astype(str).str.lower()

In [ ]:
df_clientes_limpo['status cliente'].value_counts()

status cliente
ativo      1003
inativo     997
Name: count, dtype: int64